In [1]:
import torch

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
print(x)
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
# 将张量按照行方合并
torch.cat((x,y),dim=0)
# 将张量按照列方合并


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [7]:
torch.cat((x,y),dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [9]:
torch.cat((x,y),dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [ ]:
# 判断张量是否相等 用逻辑构建一个新的张量

In [11]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# 广播机制，不同的张量之间相加，或许不会得到想要的结果

In [15]:
a = torch.arange(3).reshape((3,1))

In [33]:
b = torch.arange(2).reshape((1,2))

In [35]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [ ]:
# x[-1]：访问最后一行  x[1:3]：访问第一行，第二行   x[0:2，：] = 12 ：第一行，第二行全选赋值12

In [39]:
A = x.numpy()

In [41]:
B = torch.tensor(A)

In [43]:
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [45]:
print(A)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [47]:
!pip install pandas

  Using cached pandas-2.0.3-cp38-cp38-win_amd64.whl.metadata (18 kB)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
  Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
   ---------------------------------------- 0.0/10.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.8 MB ? eta -:--:--
    --------------------------------------- 0.3/10.8 MB ? eta -:--:--
    --------------------------------------- 0.3/10.8 MB ? eta -:--:--
   -- ------------------------------------- 0.8/10.8 MB 1.2 MB/s eta 0:00:09
   --- ------------------------------------ 1.0/10.8 MB 1.4 MB/s eta 0:00:07
   --------- ------------------------------ 2.6/10.8 MB 2.8 MB/s eta 0:00:03
   ------------ --------------------------- 3.4/10.8 MB 3.0 MB/s eta 0:00:03
   -------------- ------------------------- 3.9/10.8 MB 3.

In [55]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') # 列名
    f.write('NA,Pave,127500\n') # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [48]:
import pandas as pd

In [57]:
data = pd.read_csv(data_file)

In [59]:
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [61]:
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [63]:
# 插值 处理缺失问题

In [78]:
inputs,outputs = data.iloc[:,0:2],data.iloc[:,2]

In [82]:
# inputs = inputs.fillna(inputs.mean())

In [104]:
inputs = pd.get_dummies(inputs,dummy_na = True,dtype=int)


In [106]:
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       NaN        True      False
1       2.0       False       True
2       4.0       False       True
3       NaN       False       True
